### ISSUE TITLE
add support for redis cache

### ISSUE THREAD

**Issue by iamsinghrajat** [iamsinghrajat/async-cache#3]
Need to add support for caching using redis

**Comment by karthikn82** [comment]
Wanted to know if this still needs help

**Comment by iamsinghrajat** [comment]
@karthikn82 it would be great if u can add support for redis cache.

**Comment by sahven** [comment]
Hi, I'm new to open-source dev. Please let me know if this is still open. If it is, where and how should I start?

**Comment by iamsinghrajat** [comment]
@sahven hope this a great first step for you. You can start with this open issue: [https://github.com/iamsinghrajat/async-cache/issues/4](url).

**Comment by sahven** [comment]
Though not relevant to this issue - I was going through the setitem method, and had a doubt. If the key already exists, shouldn't we first move it to the end and then make a call to super().__setitem__(key, value) ? Please correct me if I am wrong.

**Comment by iamsinghrajat** [comment]
@sahven I don't know if i understood you correctly. But if the key already exists we don't make any call to  `super().setitem(key, value)`. This `func` is called only for the first time a key is inserted in the `cache` .

**Comment by sahven** [comment]
Oh, so we can't overwrite the value to an already existing key? Because if we're overwriting the value, then we should move it to the end, right?
Something along the lines of the following - 
```python
def __setitem__(self, key, value):
       # Check if key already exists, if it does, then first move it to the end
       # and then overwrite using super().__setitem__(key,value)
        if key in self:
            self.move_to_end(key)
        super().__setitem__(key, value)
        if len(self) > self.maxsize:
            oldest = next(iter(self))
            del self[oldest]
```

**Comment by iamsinghrajat** [comment]
@sahven yes correct if we had any flow where we overwrite values for a key, this would correct solution. But currently there is no such flow where the value for key is overwritten.

**Comment by karthikn82** [comment]
@iamsinghrajat  do u have any bugs that i could work on ? just to start with

**Comment by karthikn82** [comment]
Can you list down all the functionalities that we need to implement ? I can take a few and do it
