### ISSUE TITLE
`SyntaxError: invalid syntax` in import statement

### ISSUE THREAD

**Issue by supermodo** [iamsinghrajat/async-cache#5]
I get this error when i try to run the code with import like `from async-cache import AsyncLRU`.
```
  File "app/workers/simulator.py", line 7
    from async-cache import AsyncLRU
         ^
SyntaxError: invalid syntax
```
Look like the `-` in the name is the problem.
In vsc I see the two world `async`and `cache` in different colors as lint flag it as error.
![image](https://user-images.githubusercontent.com/3813726/93517530-e2ab2b80-f92b-11ea-8990-d0aaa045d128.png)

Is this a bug or am I doing something wrong?

**Comment by codingcosmonaut** [comment]
you need to use `from cache import AsyncLRU`

**Comment by supermodo** [comment]
@codingcosmonaut it didn't seem to work, i get this error:
```
   …
   from cache import AsyncLRU
ModuleNotFoundError: No module named 'cache'
```
are you successfully using it with this syntax?

**Comment by codingcosmonaut** [comment]
I noticed this after installing the package in my environment. It's still using old src folder name.

![image](https://user-images.githubusercontent.com/71237908/95004533-9418b500-05ec-11eb-810b-91e5dbed0600.png)

@iamsinghrajat I think you need to update the PyPI version of the package with the latest changes.

**Comment by iamsinghrajat** [comment]
@codingcosmonaut & @supermodo Apologies for late reply. Latest Release of [async-cache 1.0.0](https://pypi.org/project/async-cache/) fixes this problem and also adds new feature of caching with TTL (contributed by @caidenlemiha ).
