### ISSUE TITLE
maxsize support for AsyncTTL

### ISSUE THREAD

**Issue by kamikaze** [iamsinghrajat/async-cache#8]
is it possible to set maxsize for AsyncTTL as for AsyncLRU?

**Comment by iamsinghrajat** [comment]
@kamikaze, `maxsize` is currently only supported for AsyncLRU, but I agree it might also be useful with AsyncTTL.

**Comment by kamikaze** [comment]
then it will be obvious that it os enough with a single decorator with many options :)

**Comment by iamsinghrajat** [comment]
@kamikaze released `async-cache 1.1.0` with `maxsize` support for AsyncTTL.
